/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations, useScroll  } from "@react-three/drei";
import * as THREE from 'three';
import { useFrame } from "@react-three/fiber";
import lerp from "lerp";

export default function Model({ getBreak, colors, ...props }) {
  const group = useRef();
  const charRef = useRef();
  const { nodes, materials, animations } = useGLTF("/models/modelDraco.glb");
  const { actions } = useAnimations(animations, group);
  const scroll = useScroll()
  
  const [video] = useState(() => {
    const vid = document.createElement("video");
    vid.src = "/textures/videoPortFolioOne12fps.mp4";
    vid.crossOrigin = "Anonymous";
    vid.loop = true;
    vid.muted = true;
    vid.play();
    return vid;
  });

  const [video2] = useState(() => {
    const vid = document.createElement("video");
    vid.src = "/textures/videoPortFolioTwo12fps.mp4";
    vid.crossOrigin = "Anonymous";
    vid.loop = true;
    vid.muted = true;
    vid.play();
    return vid;
  });

  useFrame((state)=>{
    const section = getBreak(scroll.offset)
    materials['00 BASE BASE'].color.lerp(new THREE.Color(colors[section][0]/255, colors[section][1]/255, colors[section][2]/255), 0.05)
    // charRef.current.scale.lerp(section == 4 ? new THREE.Vector3(0.00569359,0.00569359, 0.00569359)  : new THREE.Vector3(0,0,0), 0.05)
  })

  const nodesName = Object.keys(nodes)
  console.log(nodes)
  useEffect(()=>{
    nodesName.forEach((n)=>{
        if (nodes[n].type === 'SkinnedMesh' ){
            nodes[n].frustumCulled = false
            let geo = nodes[n].geometry
            let m = new THREE.Matrix4()
            geo.boundingBox.max = new THREE.Vector3(100, 100, 100)
            geo.boundingBox.min = new THREE.Vector3(-100, -100, -100)
            geo.boundingSphere.center = new THREE.Vector3(0, 0, 0)
        }
    })

    animations.forEach((a)=>{
      actions[a.name].play()   
    })

    materials['04 AETHERYTE CRYSTAL MATERIALS.'].emissiveIntensity = 2
    materials['04 AETHERYTE CRYSTAL MATERIALS.'].emissive = new THREE.Color(18/255, 105/255, 135/255)
    materials['04 AETHERYTE CRYSTAL MATERIALS.'].emissiveMap = null
    materials['Persona Emission'].emissive = new THREE.Color("rgb(163, 43, 36)")
    materials['Persona Emission'].emissiveIntensity = 2
    materials['Persona Emission'].color = new THREE.Color("rgb(163, 43, 36)")
      
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Cloud001"
          position={[-3.3844612, 2.0842986, 0.9526216]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.1157846}
        >
          <primitive object={nodes.HipController} />
          <primitive object={nodes.Bone} />
          <group name="02_CLOUD003">
            <skinnedMesh
              name="Cube100"
              geometry={nodes.Cube100.geometry}
              material={materials["03 3D TECH MATERIAL"]}
              skeleton={nodes.Cube100.skeleton}
            />
            <skinnedMesh
              name="Cube100_1"
              geometry={nodes.Cube100_1.geometry}
              material={materials["03 Plastic.003"]}
              skeleton={nodes.Cube100_1.skeleton}
            />
            <skinnedMesh
              name="Cube100_2"
              geometry={nodes.Cube100_2.geometry}
              material={materials["03 Plastic.004"]}
              skeleton={nodes.Cube100_2.skeleton}
            />
            <skinnedMesh
              name="Cube100_3"
              geometry={nodes.Cube100_3.geometry}
              material={materials["03 Plastic.005"]}
              skeleton={nodes.Cube100_3.skeleton}
            />
            <skinnedMesh
              name="Cube100_4"
              geometry={nodes.Cube100_4.geometry}
              material={materials["03 Plastic.006"]}
              skeleton={nodes.Cube100_4.skeleton}
            />
            <skinnedMesh
              name="Cube100_5"
              geometry={nodes.Cube100_5.geometry}
              material={materials["03 Plastic.007"]}
              skeleton={nodes.Cube100_5.skeleton}
            />
          </group>
        </group>
        <group
          name="Torb003"
          position={[-3.3373015, 4.096097, -3.3434596]}
          rotation={[Math.PI, -0.0945457, Math.PI]}
          scale={[1.269866, 1.2698656, 1.269866]}
        >
          <primitive object={nodes.FootC} />
          <primitive object={nodes.Bone_1} />
          <primitive object={nodes.FootD} />
          <primitive object={nodes.Foot_A} />
          <primitive object={nodes.FootB} />
          <group name="Base_Bottom003">
            <skinnedMesh
              name="Cylinder062"
              geometry={nodes.Cylinder062.geometry}
              material={materials["04 HELMET TORB PERS"]}
              skeleton={nodes.Cylinder062.skeleton}
            />
            <skinnedMesh
              name="Cylinder062_1"
              geometry={nodes.Cylinder062_1.geometry}
              material={materials["Black Metal"]}
              skeleton={nodes.Cylinder062_1.skeleton}
            />
          </group>
          <skinnedMesh
            name="Cube019"
            geometry={nodes.Cube019.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Cube019.skeleton}
          />
          <skinnedMesh
            name="Feet_Cover005"
            geometry={nodes.Feet_Cover005.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet_Cover005.skeleton}
          />
          <skinnedMesh
            name="Feet_Cover006"
            geometry={nodes.Feet_Cover006.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet_Cover006.skeleton}
          />
          <skinnedMesh
            name="Feet_Cover007"
            geometry={nodes.Feet_Cover007.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet_Cover007.skeleton}
          />
          <skinnedMesh
            name="Feet_Cover008"
            geometry={nodes.Feet_Cover008.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet_Cover008.skeleton}
          />
          <skinnedMesh
            name="Feet005"
            geometry={nodes.Feet005.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet005.skeleton}
          />
          <skinnedMesh
            name="Feet006"
            geometry={nodes.Feet006.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet006.skeleton}
          />
          <skinnedMesh
            name="Feet007"
            geometry={nodes.Feet007.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet007.skeleton}
          />
          <skinnedMesh
            name="Feet008"
            geometry={nodes.Feet008.geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes.Feet008.skeleton}
          />
          <skinnedMesh
            name="Leg-1005"
            geometry={nodes["Leg-1005"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-1005"].skeleton}
          />
          <skinnedMesh
            name="Leg-1006"
            geometry={nodes["Leg-1006"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-1006"].skeleton}
          />
          <skinnedMesh
            name="Leg-1007"
            geometry={nodes["Leg-1007"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-1007"].skeleton}
          />
          <skinnedMesh
            name="Leg-1008"
            geometry={nodes["Leg-1008"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-1008"].skeleton}
          />
          <skinnedMesh
            name="Leg-2005"
            geometry={nodes["Leg-2005"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-2005"].skeleton}
          />
          <skinnedMesh
            name="Leg-2006"
            geometry={nodes["Leg-2006"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-2006"].skeleton}
          />
          <skinnedMesh
            name="Leg-2007"
            geometry={nodes["Leg-2007"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-2007"].skeleton}
          />
          <skinnedMesh
            name="Leg-2008"
            geometry={nodes["Leg-2008"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Leg-2008"].skeleton}
          />
          <skinnedMesh
            name="Turret-Top-2003"
            geometry={nodes["Turret-Top-2003"].geometry}
            material={materials["04 HELMET TORB PERS"]}
            skeleton={nodes["Turret-Top-2003"].skeleton}
          >
            <skinnedMesh
              name="Turret_Top003"
              geometry={nodes.Turret_Top003.geometry}
              material={materials["04 HELMET TORB PERS"]}
              skeleton={nodes.Turret_Top003.skeleton}
            >
              <skinnedMesh
                name="Cylinder035"
                geometry={nodes.Cylinder035.geometry}
                material={materials["04 HELMET TORB PERS"]}
                skeleton={nodes.Cylinder035.skeleton}
              />
              <skinnedMesh
                name="Cylinder036"
                geometry={nodes.Cylinder036.geometry}
                material={materials["04 HELMET TORB PERS"]}
                skeleton={nodes.Cylinder036.skeleton}
              />
              <skinnedMesh
                name="Plane012"
                geometry={nodes.Plane012.geometry}
                material={materials["04 HELMET TORB PERS"]}
                skeleton={nodes.Plane012.skeleton}
              />
              <skinnedMesh
                name="Plane018"
                geometry={nodes.Plane018.geometry}
                material={materials["04 HELMET TORB PERS"]}
                skeleton={nodes.Plane018.skeleton}
              />
              <skinnedMesh
                name="Plane019"
                geometry={nodes.Plane019.geometry}
                material={materials["04 HELMET TORB PERS"]}
                skeleton={nodes.Plane019.skeleton}
              />
              <skinnedMesh
                name="Turret_Top006"
                geometry={nodes.Turret_Top006.geometry}
                material={materials["04 HELMET TORB PERS"]}
                skeleton={nodes.Turret_Top006.skeleton}
              />
            </skinnedMesh>
          </skinnedMesh>
        </group>
        <group
          name="DANCING_MAN"
          position={[0.6141291, 0.0250709, 0]}
          rotation={[Math.PI / 2, -1e-7, -0.6855818]}
          scale={0.0056936}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="CharacterModel007"
            geometry={nodes.CharacterModel007.geometry}
            material={materials.CHARACTER}
            skeleton={nodes.CharacterModel007.skeleton}
          />
        </group>
        <group
          name="Empty002"
          position={[-3.1367228, 1.2973946, -1.7378774]}
          rotation={[Math.PI / 2, 1.0028749, -Math.PI / 2]}
          scale={1.3849726}
        >
          <mesh
            name="04-2-2_AST002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_AST002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.1994845, -0.0100566, 0.2322757]}
            rotation={[0, -0.1635319, 0]}
            scale={[0.590949, 0.5909492, 0.5909492]}
          />
          <mesh
            name="04-2-2_BOSS002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_BOSS002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.0781399, -0.0042484, -0.2481375]}
          />
          <mesh
            name="04-2-2_DNC003"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_DNC003"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[0.1748835, -0.0128208, 0.1681603]}
            rotation={[0, 0.4858295, 0]}
            scale={[0.5909494, 0.5909493, 0.5909494]}
          />
          <mesh
            name="04-2-2_EW_BOARD002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_EW_BOARD002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.0655494, -0.0942528, 0.0139312]}
            rotation={[Math.PI, -1.5702387, Math.PI]}
          >
            <mesh
              name="Cube015"
              castShadow
              receiveShadow
              geometry={nodes.Cube015.geometry}
              material={materials["04 EW BOARD AND GHOST"]}
              position={[-0.0014524, 0.0105435, -0.001324]}
            />
          </mesh>
          <mesh
            name="04-2-2_GNB002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_GNB002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.0748274, -0.0140221, 0.2915823]}
            scale={0.5909498}
          />
          <mesh
            name="04-2-2_NIN002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_NIN002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[0.0508042, -0.0148304, 0.338171]}
            rotation={[0, 0.1440985, 0]}
            scale={0.5909498}
          />
          <mesh
            name="04-2-2_RDM002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_RDM002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.3192111, -0.014022, 0.1918397]}
            rotation={[0, -0.409311, 0]}
            scale={[0.5909492, 0.5909498, 0.5909497]}
          />
          <mesh
            name="04-2-2_SAM002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_SAM002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.1965876, -0.0140221, 0.3534046]}
            rotation={[0, -0.1338596, 0]}
            scale={0.5909498}
          />
          <mesh
            name="04-2-2_WAR002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_WAR002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[-0.0764481, -0.0140221, 0.1721616]}
            rotation={[Math.PI, -3e-7, Math.PI]}
            scale={0.5909498}
          />
          <mesh
            name="04-2-2_WHM002"
            castShadow
            receiveShadow
            geometry={nodes["04-2-2_WHM002"].geometry}
            material={materials["04 EW BOARD AND GHOST"]}
            position={[0.0481601, -0.0133382, 0.2200146]}
            rotation={[0, 0.1893208, 0]}
            scale={[0.5909489, 0.5909492, 0.5909492]}
          />
        </group>
        <group
          name="04-2-1_EMPTY002"
          position={[-3.0163763, 0.9967277, -0.2096521]}
          scale={0.2901334}
        >
          <group
            name="Cylinder032"
            position={[1.1463308, 1.0713003, -0.1067939]}
          >
            <mesh
              name="Cylinder057"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder057.geometry}
              material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
            />
            <mesh
              name="Cylinder057_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder057_1.geometry}
              material={materials["04 AETHERYTE MATERIALS"]}
            />
          </group>
          <group
            name="Cylinder033"
            position={[-0.9501143, 1.048919, 0.5405349]}
            rotation={[Math.PI, -0.4101273, Math.PI]}
          >
            <mesh
              name="Cylinder058"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder058.geometry}
              material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
            />
            <mesh
              name="Cylinder058_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder058_1.geometry}
              material={materials["04 AETHERYTE MATERIALS"]}
            />
          </group>
        </group>
        <mesh
          name="00_BASE_BASE002"
          castShadow
          receiveShadow
          geometry={nodes["00_BASE_BASE002"].geometry}
          material={materials["BASE BASE BASE"]}
          position={[0.8386995, -0.2744737, 1.0874903]}
        />
        <mesh
          name="00_WALLS002"
          castShadow
          receiveShadow
          geometry={nodes["00_WALLS002"].geometry}
          material={materials["00 FLOOR AND WALLS"]}
          position={[-0.2547808, -0.0567794, -0.8917942]}
        />
        <mesh
          name="00_FLOOR002"
          castShadow
          receiveShadow
          geometry={nodes["00_FLOOR002"].geometry}
          material={materials["00 FLOOR AND WALLS"]}
          position={[0.3236995, -0.0183779, -4.0815749]}
        />
        <mesh
          name="00_STAND002"
          castShadow
          receiveShadow
          geometry={nodes["00_STAND002"].geometry}
          material={materials["00 FLOOR AND WALLS"]}
          position={[0.2912102, 0.6274283, -3.1820564]}
          scale={[0.0785947, 0.659003, 0.0785947]}
        />
        <mesh
          name="04_SHELF_1001"
          castShadow
          receiveShadow
          geometry={nodes["04_SHELF_1001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-3.3547804, 2.8972192, -2.1566634]}
        />
        <mesh
          name="04_SHELF_2001"
          castShadow
          receiveShadow
          geometry={nodes["04_SHELF_2001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-3.3010435, 2.3375864, -2.9619076]}
        />
        <mesh
          name="04_SHELF_3001"
          castShadow
          receiveShadow
          geometry={nodes["04_SHELF_3001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-3.3010435, 3.8802004, -2.9619076]}
        />
        <mesh
          name="01_DESK001"
          castShadow
          receiveShadow
          geometry={nodes["01_DESK001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[2.533411, 1.4028308, -3.7495711]}
        />
        <mesh
          name="03_FRAME_2001"
          castShadow
          receiveShadow
          geometry={nodes["03_FRAME_2001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-0.7600815, 2.6782866, -4.4365263]}
        />
        <mesh
          name="03_FRAME_3001"
          castShadow
          receiveShadow
          geometry={nodes["03_FRAME_3001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-1.996263, 3.2082, -4.4365263]}
        />
        <mesh
          name="03_FRAME_1001"
          castShadow
          receiveShadow
          geometry={nodes["03_FRAME_1001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-0.9124001, 4.2553072, -4.4365263]}
        />
        <mesh
          name="02_3D_TECH_SHELF001"
          castShadow
          receiveShadow
          geometry={nodes["02_3D_TECH_SHELF001"].geometry}
          material={materials["00 BASE BASE"]}
          position={[-3.2904794, 0.9104593, 1.7902007]}
        />
        <mesh
          name="00_BASE002"
          castShadow
          receiveShadow
          geometry={nodes["00_BASE002"].geometry}
          material={materials["00 BASE BASE"]}
          position={[0, -0.0567794, -0.8036153]}
        />
        <mesh
          name="GHOST"
          castShadow
          receiveShadow
          geometry={nodes.GHOST.geometry}
          material={materials["04 EW BOARD AND GHOST"]}
          position={[-3.2213476, 2.776201, -3.3075156]}
          rotation={[0, 1.1160613, 0]}
          scale={[1.453003, 1.4530029, 1.453003]}
        />
        <group
          name="Monitor1001"
          position={[1.121271, 1.7176379, -3.9833994]}
          rotation={[-Math.PI, 1.5082734, -Math.PI]}
        >
          <mesh
            name="Cube102"
            castShadow
            receiveShadow
            geometry={nodes.Cube102.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
          />
          <mesh
            name="Cube102_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube102_1.geometry}
            material={materials["01 COMPUTER SCREEN"]}
          />
        </group>
        <group
          name="Monitor2001"
          position={[2.6281116, 2.0253193, -4.0198193]}
          rotation={[0, -0.2039718, 0]}
        >
          <mesh
            name="Cube103"
            castShadow
            receiveShadow
            geometry={nodes.Cube103.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
          />
          <mesh
            name="Cube103_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube103_1.geometry}
            material={materials["01 COMPUTER SCREEN"]}
          />
        </group>
        <group name="MousPad001" position={[1.8692856, 1.5055722, -3.2205727]}>
          <mesh
            name="Plane032"
            castShadow
            receiveShadow
            geometry={nodes.Plane032.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
          />
          <mesh
            name="Plane032_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane032_1.geometry}
            material={materials["01 MOUSEPAD EMISSION"]}
          />
        </group>
        <mesh
          name="Keyboard001"
          castShadow
          receiveShadow
          geometry={nodes.Keyboard001.geometry}
          material={materials["01 DESK OBJECTS MATERIAL"]}
          position={[1.6708305, 1.5333407, -3.2339003]}
          rotation={[0.1117278, -0.1136649, 0.0127245]}
          scale={1.3187213}
        />
        <group
          name="CPU001"
          position={[2.9470181, 0.5707614, -3.4579566]}
          rotation={[0, -1.5705347, 0]}
        >
          <mesh
            name="Cube117"
            castShadow
            receiveShadow
            geometry={nodes.Cube117.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
          />
          <mesh
            name="Cube117_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube117_1.geometry}
            material={materials["01 CPU LIGHT"]}
          />
        </group>
        <group
          name="Speaker1001"
          position={[3.2765994, 1.6700684, -3.7217181]}
          rotation={[Math.PI, -1.2287722, Math.PI]}
        >
          <mesh
            name="Cube118"
            castShadow
            receiveShadow
            geometry={nodes.Cube118.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
          />
          <mesh
            name="Cube118_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube118_1.geometry}
            material={materials["0X_Steel_Scratched_mqm"]}
          />
        </group>
        <group
          name="Speaker2001"
          position={[0.1012144, 1.6688697, -3.6814764]}
          rotation={[0, -1.1618309, 0]}
        >
          <mesh
            name="Cube119"
            castShadow
            receiveShadow
            geometry={nodes.Cube119.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
          />
          <mesh
            name="Cube119_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube119_1.geometry}
            material={materials["0X_Steel_Scratched_mqm"]}
          />
        </group>
        <mesh
          name="BezierCurve001"
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve001.geometry}
          material={materials["01 DESK OBJECTS MATERIAL"]}
          position={[1.9486332, 1.5509846, -3.3624182]}
        />
        <mesh
          name="MOUSE001"
          castShadow
          receiveShadow
          geometry={nodes.MOUSE001.geometry}
          material={materials["01 DESK OBJECTS MATERIAL"]}
          position={[2.5632606, 1.5548788, -3.2068956]}
          rotation={[0, 0.3184926, 0]}
        >
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
            position={[-0.1106142, -0.0084484, 0.0259503]}
          />
          <mesh
            name="Cylinder003"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials["01 DESK OBJECTS MATERIAL"]}
            position={[-0.0160036, 0.0357739, -0.076062]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </mesh>
        <mesh
          name="3D_Printer002"
          castShadow
          receiveShadow
          geometry={nodes["3D_Printer002"].geometry}
          material={materials["03 3D TECH MATERIAL"]}
          position={[-2.8303156, 1.9234607, 1.5585896]}
          rotation={[-Math.PI, 1.5534626, -Math.PI]}
          scale={0.1536194}
        >
          <mesh
            name="BezierCurve003"
            castShadow
            receiveShadow
            geometry={nodes.BezierCurve003.geometry}
            material={materials["03 Plastic.001"]}
            position={[-6.2203169, 1.8340807, -2.8381808]}
            rotation={[0, 0, -3.0779989]}
            scale={[13.7339802, 13.7339783, 13.7339802]}
          />
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials["03 3D TECH MATERIAL"]}
            position={[-0.6689419, 2.7203493, -2.1598492]}
            scale={[13.7339802, 13.7339783, 13.7339802]}
          >
            <group
              name="Cube011"
              position={[-0.1830904, -0.0093817, 0.0383593]}
            >
              <mesh
                name="Cube097"
                castShadow
                receiveShadow
                geometry={nodes.Cube097.geometry}
                material={materials["03 3D TECH MATERIAL"]}
              />
              <mesh
                name="Cube097_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube097_1.geometry}
                material={materials["0T_Brass_mqm"]}
              />
              <mesh
                name="Cube097_2"
                castShadow
                receiveShadow
                geometry={nodes.Cube097_2.geometry}
                material={materials["0D_Metal_Dark_mqm"]}
              />
            </group>
          </mesh>
          <mesh
            name="Cube008"
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials["03 3D TECH MATERIAL"]}
            position={[-4.3080063, 7.2593012, -2.2300727]}
            scale={[13.7339802, 13.7339783, 13.7339802]}
          >
            <mesh
              name="Cylinder021"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder021.geometry}
              material={materials["03 3D TECH MATERIAL"]}
              position={[-0.001292, 0.0623268, -0.0494755]}
            />
          </mesh>
          <mesh
            name="Cylinder015"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder015.geometry}
            material={materials["03 Plastic.001"]}
            position={[-4.3406463, 8.1047964, -2.907871]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[13.7339802, 13.7339802, 13.7339783]}
          />
          <mesh
            name="Logo002"
            castShadow
            receiveShadow
            geometry={nodes.Logo002.geometry}
            material={materials["03 3D TECH MATERIAL"]}
            position={[-2.8125887, 0.018342, -2.399972]}
            scale={[13.7339802, 13.7339783, 13.7339802]}
          >
            <mesh
              name="Cube010"
              castShadow
              receiveShadow
              geometry={nodes.Cube010.geometry}
              material={materials["03 3D TECH MATERIAL"]}
              position={[0.0107941, -0.0250345, -0.0395347]}
            />
            <mesh
              name="Cube012"
              castShadow
              receiveShadow
              geometry={nodes.Cube012.geometry}
              material={materials["03 Plastic.001"]}
              morphTargetDictionary={nodes.Cube012.morphTargetDictionary}
              morphTargetInfluences={nodes.Cube012.morphTargetInfluences}
              position={[-0.002498, 0.0085181, 0.0093301]}
              rotation={[-Math.PI, 0.0175249, -Math.PI]}
              scale={[0.4999585, 0.4999586, 0.4999585]}
            />
          </mesh>
        </mesh>
        <group
          name="body002"
          position={[-2.9149776, 2.0564198, 1.0839731]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.6908351}
        >
          <mesh
            name="Cylinder026_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026_1.geometry}
            material={materials["03 3D TECH MATERIAL"]}
          />
          <mesh
            name="Cylinder026_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026_2.geometry}
            material={materials["03 Plastic.007"]}
          />
        </group>
        <group
          name="feet004"
          position={[-2.9053442, 1.9342763, 1.0975245]}
          rotation={[1.5797268, 0.0287146, 0.2703197]}
          scale={0.6908351}
        >
          <mesh
            name="Cylinder024"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder024.geometry}
            material={materials["03 3D TECH MATERIAL"]}
          />
          <mesh
            name="Cylinder024_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder024_1.geometry}
            material={materials["03 Plastic.006"]}
          />
          <mesh
            name="Cylinder024_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder024_2.geometry}
            material={materials["03 Plastic.007"]}
          />
          <mesh
            name="Cylinder024_3"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder024_3.geometry}
            material={materials["03 Plastic.011"]}
          />
        </group>
        <mesh
          name="feet005"
          castShadow
          receiveShadow
          geometry={nodes.feet005.geometry}
          material={materials["03 3D TECH MATERIAL"]}
          position={[-2.9418528, 1.7569673, 1.0429947]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.6908351}
        />
        <mesh
          name="hands002"
          castShadow
          receiveShadow
          geometry={nodes.hands002.geometry}
          material={materials["03 3D TECH MATERIAL"]}
          position={[-2.9660118, 1.9310546, 1.1096697]}
          rotation={[-2.2707393, Math.PI / 2, 0]}
          scale={0.6908351}
        />
        <group
          name="hat002"
          position={[-3.0174685, 2.307426, 1.1178665]}
          rotation={[0, 0, 0.2946494]}
          scale={0.6908351}
        >
          <mesh
            name="Cylinder017"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017.geometry}
            material={materials["03 3D TECH MATERIAL"]}
          />
          <mesh
            name="Cylinder017_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017_1.geometry}
            material={materials["03 Plastic.001"]}
          />
        </group>
        <group
          name="head002"
          position={[-2.9631784, 2.1454, 1.1178665]}
          scale={0.6908351}
        >
          <mesh
            name="Sphere005"
            castShadow
            receiveShadow
            geometry={nodes.Sphere005.geometry}
            material={materials["03 3D TECH MATERIAL"]}
          />
          <mesh
            name="Sphere005_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere005_1.geometry}
            material={materials["03 Plastic.003"]}
          />
        </group>
        <mesh
          name="torso002"
          castShadow
          receiveShadow
          geometry={nodes.torso002.geometry}
          material={materials["03 3D TECH MATERIAL"]}
          position={[-2.954715, 2.0333383, 1.104903]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.6908351}
        />
        <mesh
          name="04-3-2_HELMET002"
          castShadow
          receiveShadow
          geometry={nodes["04-3-2_HELMET002"].geometry}
          material={materials["04 HELMET TORB PERS"]}
          position={[-3.3229134, 2.601089, -2.1871462]}
          rotation={[-0.0148549, 0.0043926, 0.0701674]}
          scale={[1.3415703, 1.3415704, 1.3415701]}
        />
        <mesh
          name="04-3-1_PERSONA002"
          castShadow
          receiveShadow
          geometry={nodes["04-3-1_PERSONA002"].geometry}
          material={materials["04 HELMET TORB PERS"]}
          position={[-3.3197899, 2.7826338, -1.1126578]}
          rotation={[0, -0.0887397, 0]}
          scale={1.3312995}
        >
          <mesh
            name="Plane008"
            castShadow
            receiveShadow
            geometry={nodes.Plane008.geometry}
            material={materials["04 HELMET TORB PERS"]}
            position={[0, 0.0300441, 0.0530668]}
            rotation={[2.0370763, 0, 0]}
          />
          <mesh
            name="Vert002"
            castShadow
            receiveShadow
            geometry={nodes.Vert002.geometry}
            material={materials["Persona Emission"]}
            morphTargetDictionary={nodes.Vert002.morphTargetDictionary}
            morphTargetInfluences={nodes.Vert002.morphTargetInfluences}
            position={[0.1600142, -0.1534166, 0.1077563]}
            rotation={[0, 0, -0.1176443]}
          />
        </mesh>
        <mesh
          name="04-2-3_SPIRAL002"
          castShadow
          receiveShadow
          geometry={nodes["04-2-3_SPIRAL002"].geometry}
          material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
          position={[-3.0960841, 1.0556449, -3.0510604]}
          scale={1.3421408}
        />
        <mesh
          name="04-2-3_BODY002"
          castShadow
          receiveShadow
          geometry={nodes["04-2-3_BODY002"].geometry}
          material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
          position={[-3.1100955, 1.6641215, -3.0833261]}
          scale={[1.3421412, 1.3421408, 1.3421412]}
        >
          <mesh
            name="gold_spiral_1001"
            castShadow
            receiveShadow
            geometry={nodes.gold_spiral_1001.geometry}
            material={materials["04 AETHERYTE MATERIALS"]}
            position={[0.028441, -0.1736966, 0.0455186]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </mesh>
        <mesh
          name="04-2-3_EW_OUTER002"
          castShadow
          receiveShadow
          geometry={nodes["04-2-3_EW_OUTER002"].geometry}
          material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
          position={[-3.0904596, 1.6502042, -3.0865757]}
          rotation={[0, -0.9776427, -0.7087179]}
          scale={[1.3421409, 1.3421408, 1.3421408]}
        >
          <mesh
            name="Circle011"
            castShadow
            receiveShadow
            geometry={nodes.Circle011.geometry}
            material={materials["04 AETHERYTE MATERIALS"]}
          />
        </mesh>
        <group
          name="04-2-3_BASE002"
          position={[-3.1031973, 0.6684804, -3.0833764]}
          scale={1.3421408}
        >
          <mesh
            name="Cylinder027"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027.geometry}
            material={materials["04 AETHERYTE MATERIALS"]}
          />
          <mesh
            name="Cylinder027_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_1.geometry}
            material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
          />
        </group>
        <mesh
          name="04-2-3_EW_AETHER002"
          castShadow
          receiveShadow
          geometry={nodes["04-2-3_EW_AETHER002"].geometry}
          material={materials["04 AETHERYTE MATERIALS"]}
          position={[-3.0868914, 1.6566886, -3.0831912]}
          rotation={[0, 0, -0.5155841]}
          scale={[1.3421408, 1.3421407, 1.3421412]}
        >
          <mesh
            name="Circle007"
            castShadow
            receiveShadow
            geometry={nodes.Circle007.geometry}
            material={materials["04 AETHERYTE MATERIALS"]}
            position={[0.3061125, 0.0086792, 0.0035036]}
            rotation={[Math.PI / 2, 0.5155841, -2e-7]}
          />
          <mesh
            name="Circle010"
            castShadow
            receiveShadow
            geometry={nodes.Circle010.geometry}
            material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
            position={[0, 0, 0.0345595]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </mesh>
        <mesh
          name="04-2-3_HOOP002"
          castShadow
          receiveShadow
          geometry={nodes["04-2-3_HOOP002"].geometry}
          material={materials["04 AETHERYTE MATERIALS"]}
          position={[-3.0912995, 1.128006, -3.0847774]}
          rotation={[0, 0, 0.2295941]}
          scale={[1.3421407, 1.342141, 1.3421408]}
        />
        <group
          name="04-2-1_Aetheryte_Base002"
          position={[-3.0163763, 0.5420296, -0.2096521]}
          rotation={[0, -0.0012358, 0]}
          scale={[1.4300339, 1.4300338, 1.4300339]}
        >
          <mesh
            name="Cylinder029"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder029.geometry}
            material={materials["04 AETHERYTE MATERIALS"]}
          />
          <mesh
            name="Cylinder029_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder029_1.geometry}
            material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
          />
          <mesh
            name="Cylinder034"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder034.geometry}
            material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
            position={[0, 0.6801773, 0]}
            rotation={[0, 0.0012358, 0]}
          />
        </group>
        <group
          name="04-2-1_Aetehryte_Body002"
          position={[-3.0163763, 0.9967277, -0.2096521]}
          scale={[1.4300339, 1.4300338, 1.4300339]}
        >
          <mesh
            name="Cylinder038"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder038.geometry}
            material={materials["04 AETHERYTE MATERIALS"]}
          />
          <mesh
            name="Cylinder038_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder038_1.geometry}
            material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
          />
          <mesh
            name="Cylinder026"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026.geometry}
            material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
            position={[0, 0.1492684, 0]}
          />
        </group>
        <mesh
          name="Aetheryte_Hoop_Spin001"
          castShadow
          receiveShadow
          geometry={nodes.Aetheryte_Hoop_Spin001.geometry}
          material={materials["04 AETHERYTE MATERIALS"]}
          position={[-3.0163763, 1.5276533, -0.2096521]}
          rotation={[-2.6663291, -3e-7, -Math.PI]}
          scale={[1.4300338, 1.4300339, 1.4300339]}
        >
          <group
            name="Cylinder028"
            position={[0, 0.0000492, -0.4314928]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.2028857}
          >
            <mesh
              name="Cylinder056"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder056.geometry}
              material={materials["04 AETHERYTE MATERIALS"]}
            />
            <mesh
              name="Cylinder056_1"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder056_1.geometry}
              material={materials["04 AETHERYTE CRYSTAL MATERIALS."]}
            />
          </group>
        </mesh>
        <mesh
          name="SATELLITE001"
          castShadow
          receiveShadow
          geometry={nodes.SATELLITE001.geometry}
          material={materials["02 GEO MATERIALS"]}
          position={[-1.0770181, 4.1186662, -4.4708767]}
          rotation={[3.1079245, 0.2154771, -2.3613958]}
          scale={0.1732502}
        >
          <mesh
            name="Cone003"
            castShadow
            receiveShadow
            geometry={nodes.Cone003.geometry}
            material={materials["02 GEO MATERIALS"]}
            position={[0.000052, -0.5954285, 0.0002586]}
            rotation={[-Math.PI, 0.0252132, 0]}
            scale={[1, 0.7385844, 1]}
          />
          <mesh
            name="Cylinder010"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials["02 GEO MATERIALS"]}
            position={[0.0005336, -1.1344969, 0.0035353]}
            rotation={[0, 0.2180518, 0]}
            scale={0.0789127}
          />
          <mesh
            name="Plane004"
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={materials["02 GEO MATERIALS"]}
            position={[1.4136324, 1.5642989, -0.1179866]}
            rotation={[1.6307985, -0.0132862, 0.0253371]}
          />
        </mesh>
        <mesh
          name="Mountains001"
          castShadow
          receiveShadow
          geometry={nodes.Mountains001.geometry}
          material={materials["02 GEO MATERIALS"]}
          morphTargetDictionary={nodes.Mountains001.morphTargetDictionary}
          morphTargetInfluences={nodes.Mountains001.morphTargetInfluences}
          position={[-0.9544943, 2.0008698, -4.6025252]}
          scale={[1.2689942, 0.7860936, 0.2443921]}
        />
        <mesh
          name="Plane005"
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials["02 GEO MATERIALS"]}
          position={[-1.6879967, 3.1910844, -5.1801591]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.645304}
        />
        <mesh
          name="Moon"
          castShadow
          receiveShadow
          geometry={nodes.Moon.geometry}
          material={materials["Material.003"]}
          position={[-2.0011201, 3.1243999, -4.6337991]}
          rotation={[-0.1179274, 0.3334652, -3.1028322]}
          scale={[0.3852556, 0.3852556, 0.3852555]}
        />
      </group>
    </group>
  );
}
useGLTF.preload("/models/modelDraco.glb");
